### ISSUE TITLE
Does not seem to work

### ISSUE THREAD

**Issue by jbatesmd** [mykle1/MMM-MARS#1]
I installed this module along with the one that displays the hubble images but thus far it doesnt seem to work.  The hubble images come across just fine.  I dont get an error message while the config file is loading.

**Comment by mykle1** [comment]
Hi, I'm sorry that you are having trouble with this module. I just installed it on several machines and it fires right up. If you create a topic on the MagicMirror forum I can better help you there. I'll have you up and running in no time. Peace!
